[package]
name = "merk"
description = "Merkle key/value store"
version = "1.0.0-alpha.9"
authors = ["Matt Bell <mappum@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
time = "0.1.42"
hex = "0.4.2"
colored = "1.8.0"
num_cpus = "1.10.0"
byteorder = "1.3.2"
jemallocator = "0.3.2"
failure = "0.1.6"
clap = { git = "https://github.com/clap-rs/clap" }

[dependencies.blake2-rfc]
version = "0.2.18"
features = ["bench", "simd_asm"]

[dependencies.rand]
version = "0.7.0"
features = ["small_rng"]

[dependencies.rocksdb]
package = "mappum-rocksdb"
version = "0.14.0-alpha.1"
default-features = false

[[bin]]
name = "diff"
path = "./bin/diff.rs"
