[package]
name = "rust"
version = "0.1.0"
authors = ["Matt Bell <mappum@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.91"
bincode = "1.1.3"
serde_derive = "1.0.91"
time = "0.1.42"
rocksdb = "0.12.2"
rand = "0.6.5"
